# Generated by Django 5.2.6 on 2025-09-16 15:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Baseyn nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Soatlik narx (so'm)")),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Sig'im (nechta odam)")),
                ('opening_time', models.TimeField(verbose_name='Ochilish vaqti')),
                ('closing_time', models.TimeField(verbose_name='Yopilish vaqti')),
                ('has_sauna', models.BooleanField(default=False, verbose_name='Sauna bor')),
                ('has_cafe', models.BooleanField(default=False, verbose_name='Kafe bor')),
                ('has_sports_area', models.BooleanField(default=False, verbose_name='Sport maydoni bor')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking bor')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi bor')),
                ('children_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Bolalar uchun chegirma (%)')),
                ('group_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Guruh uchun chegirma (%)')),
                ('rules', models.TextField(blank=True, verbose_name='Qoidalar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Baseyn',
                'verbose_name_plural': 'Baseynlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateField(verbose_name='Buyurtma sanasi')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('duration_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Davomiyligi (soat)')),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Odamlar soni')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Mijoz ismi')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('customer_address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('customer_age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Asosiy narx')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirma miqdori')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Yakunlangan')], default='pending', max_length=20, verbose_name='Holat')),
                ('special_requests', models.TextField(blank=True, verbose_name="Maxsus so'rovlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.pool', verbose_name='Baseyn')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pool_images/', verbose_name='Rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pools.pool')),
            ],
            options={
                'verbose_name': 'Baseyn rasmi',
                'verbose_name_plural': 'Baseyn rasmlari',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
